AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ServerlessCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      DBClusterIdentifier: serverless-cluster
      Engine: aurora-postgresql
      EngineMode: serverless
      MasterUsername: admin
      MasterUserPassword: supersecret123
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 16
        MinCapacity: 2
        SecondsUntilAutoPause: 300
