AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties: {CidrBlock: 10.0.0.0/16}
  SubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties: {VpcId: !Ref VPC, CidrBlock: 10.0.1.0/24, AvailabilityZone: us-east-1a}
  SubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties: {VpcId: !Ref VPC, CidrBlock: 10.0.2.0/24, AvailabilityZone: us-east-1b}
  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Primary DB Subnet Group
      SubnetIds: [!Ref SubnetA, !Ref SubnetB]
      DBSubnetGroupName: my-db-subnets
  PrimaryDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: primary-db
      AllocatedStorage: '20'
      Engine: postgres
      DBInstanceClass: db.t3.micro
      MasterUsername: dbadmin
      MasterUserPassword: supersecret123
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
